language: node_js
node_js:
- '6'
before_install:
- npm i npm-cli-login -g
- npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
- npm who
install:
- npm install
script:
- ./ci/build.js
- ./ci/shim.js
- ./ci/test.js
after_success:
- ./ci/travis/publish.js
- ./ci/travis/push_sugos_index.js
env:
  secure: "O9xA6iua75hg1MQeNqYvWwWi3chKYYoLgWly3BQ9K8xXLjrmJP8K49QpRdyHBP1fjuZa4Tj1XP+sjXmL1C6p1ooLpNK7SsXMPyfYslZSlGQCYlY2eoUPMfGlYYatT8Jk82r/p1/Zm4exhZgaGcTGyyPSZyi47Fq8eAm1qCu/8tVp/x0iha/5q6eQhtZDgmn2nU++F1lS1VpFfLAXJwkpnFolWN94QoEHyhTIcs9jQx4xFh1yXoQiJRVrwXQPd9q2j123TYgzKBo6qhUi/LZJw/eD8aBA9u3XET1rZfGebV2iD860j4986qUYNBVYLtYixSft1pKe16JDjG9CCaxL2/9Og9uwQxtfMxEA4/cCKSy3povw4b4JT/+flfZHE9eLo5vskJ0duXv9f2SQri3a0E0CZpYu6j2SkeJtTVbqfFcJTTzWnsVF1sXr9MqsCCgz2E1zg9fhwnIc64Y6eg+Yml/k+H8zV5ldyMaglVlazuEROMbzk3CPM6xekyk0DaxuAszgJkkKNrjdva/2cgJ+pgSpTkyqqxUll3yECzJn+q+5cQTPEpdzyk7gm4LjaMg6gvefWTTFYAb1Xsa3S/KMBzVNXEuEhZ0LHKbta1s40S838IcM6n7oVFnYUp5PLKVB+v8ooRp4qcdLUK7PlgZeLZRc47y/2+Fn6gc+P5Cycc8="
